local rect256 = Rect.new(Vector2.new(256, 256), Vector2.new(256, 256))

return {
	bottom_rounded = {
		center = rect256,
		id = "rbxassetid://8858987793",
	},

	rounded = {
		center = rect256,
		id = "rbxassetid://8858983293",
	},

	top_rounded = {
		center = rect256,
		id = "rbxassetid://8858987141",
	},

	rounded_values = {
		[8] = 0.03,
		[7] = 0.025,
		[6] = 0.02,
	},

	elevation = {
		[0] = 0,
		[1] = 1,
		[2] = 2,
		[3] = 3,
		[4] = 4,
		[6] = 6,
		[8] = 8,
		[9] = 9,
		[12] = 12,
		[16] = 16,
	},

	shadow_image = "rbxassetid://1316045217",
}