return {
	controls = {
		app_bar_button = require(script.controls.app_bar_button),
		app_tab_bar_button = require(script.controls.app_tab_bar_button),
		base_button = require(script.controls.base_button),
		checkbox = require(script.controls.checkbox),
		icon_button = require(script.controls.icon_button),
		icon_text_button = require(script.controls.icon_text_button),
		slider = require(script.controls.slider),
		text_button = require(script.controls.text_button),
		text_field = require(script.controls.text_field),
		toggle = require(script.controls.toggle),
	},

	views = {
		app_tab_bar = require(script.views.app_tab_bar),
		bottom_app_bar = require(script.views.bottom_app_bar),
		tooltip = require(script.views.tooltip),
		top_app_bar = require(script.views.top_app_bar),
		window = require(script.views.window),
	},

	divider = require(script.divider),
	shadow = require(script.shadow),
}
